[package]
name = "TestBoard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport="4.2.0"
sysfs_gpio = "0.6.0"
futures-util = "0.3.23"
socketcan = "1.7.0"
rand = "0.8.5"